name: sim_java_frontend
description: A school management system Flutter application.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.8.4
  url_launcher: ^6.1.11
  image_picker: ^1.0.4
  file_picker: ^10.2.0
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.2.3
  flutter_local_notifications: ^19.3.0
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_secure_storage: ^10.0.0-beta.4
  intl_phone_field: ^3.1.0
  flutter_form_builder: ^10.0.1
  formz: ^0.8.0
  url_strategy: ^0.3.0
  uuid: ^4.5.1
  table_calendar: ^3.0.8
  fl_chart: ^1.0.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^6.1.4
  logger: ^2.5.0
  flutter_spinkit: ^5.2.0
  qr_flutter: ^4.1.0
  share_plus: ^11.0.0
  flutter_slidable: ^4.0.0
  dropdown_search: ^6.0.2
  syncfusion_flutter_pdfviewer: ^29.2.11
  syncfusion_flutter_signaturepad: ^29.2.11
  syncfusion_flutter_datagrid: ^29.2.11
  syncfusion_flutter_core: ^29.2.11
  syncfusion_flutter_datepicker: ^29.2.11
  syncfusion_flutter_charts: ^29.2.11
  syncfusion_flutter_calendar: ^29.2.11+1
  syncfusion_localizations: ^29.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env

#   fonts:
#     - family: Poppins
#       fonts:
#         - asset: assets/fonts/Poppins-Regular.ttf
#         - asset: assets/fonts/Poppins-Bold.ttf
#           weight: 700
#         - asset: assets/fonts/Poppins-SemiBold.ttf
#           weight: 600
#         - asset: assets/fonts/Poppins-Medium.ttf
#           weight: 500
#         - asset: assets/fonts/Poppins-Light.ttf
#           weight: 300
