version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: simjava-postgres
    environment:
      POSTGRES_DB: simjava
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: simjava-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/simjava
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8081:8081"
    restart: unless-stopped

  # Uncomment when frontend Dockerfile is ready
  # frontend:
  #   build: ./frontend
  #   container_name: simjava-frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

volumes:
  postgres_data: 