spring:
  application:
    name: simjava-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/sistem_manajemen_sekolah
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
    baseline-version: 0
    baseline-description: Initial baseline
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    cors:
      allowed-origins: http://localhost:3000,http://localhost:8080
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

server:
  port: 8081
  servlet:
    context-path: /api

security:
  jwt:
    secret: your_very_long_secret_key_here_make_it_at_least_256_bits_long_for_security
    expiration: 86400000  # 24 hours
    refresh-expiration: 604800000  # 7 days

logging:
  level:
    root: INFO
    com.sekolah: DEBUG
    com.simjava: DEBUG
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

app:
  name: Sistem Manajemen Sekolah
  version: 1.0.0
  timezone: Asia/Jakarta
  gps:
    allowed-radius: 100
    default-latitude: -6.2088
    default-longitude: 106.8456
  file:
    upload-dir: ./uploads
    allowed-extensions: jpg,jpeg,png,pdf,doc,docx
  pagination:
    default-size: 10
    max-size: 100
  rate-limit:
    requests-per-minute: 100
    admin-requests-per-minute: 1000
  firebase:
    config-file: firebase-service-account.json
    database-url: https://simsjava-3d0d2.firebaseio.com
